# Email Configuration
mail.default.address=ace2244668@gmail.com
mail.google.app.password=zgge ezfx zozh plmv

# Database Configuration
db.url=jdbc:mysql://localhost:3306/acebank
db.user=root
db.password=2244668Aa@
db.script.path=/sql/schema_initializer.sql
db.mysql.driver=com.mysql.cj.jdbc.Driver

# SMTP Server Settings
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.connection-timeout=5000
mail.smtp.timeout=5000

sms.fast2sms.api.key=eNqweUDtrpTJztEGfNFwNvFeeUbHwGD0vBGtCB5KT6CYZsm6RjA0z8OB8w6K